Vidly/Vidly/Controllers/Api/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Vidly.DTO;
using Vidly.Models;
using AutoMapper;
using System.Data.Entity;
namespace Vidly.Controllers.Api
{
    public class MovieController : ApiController
    {
        private ApplicationDbContext _context;
        public MovieController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //Get /api/movie
        public IHttpActionResult GetMovies(string query = null)
        {
            //var movies = _context.Movies.Include(m => m.Genere).Select(Mapper.Map<MovieModel, MovieDTO>).ToList();
            //if (movies.Count == 0)
            //    return NotFound();
            var moviesQuery = _context.Movies.Include(m => m.Genere);
            if (!string.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));
            var movieDTOs = moviesQuery.Select(Mapper.Map<MovieModel, MovieDTO>);
            return Ok(movieDTOs);
        }

        //Get /api/movie/1
        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            return Ok(movie);
        }
       
        //POST /api/movie
        [HttpPost]
        public IHttpActionResult CreateMovie(MovieDTO movieDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var movie = Mapper.Map<MovieDTO, MovieModel>(movieDTO);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDTO.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDTO);
        }

        //PUT /api/movie
        [HttpPut]
        public IHttpActionResult UpdateMovie(MovieDTO movieDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var movie = _context.Movies.SingleOrDefault(m => m.Id == movieDTO.Id);
            Mapper.Map(movieDTO, movie);
            _context.SaveChanges();
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDTO);

        }

        //DELETE /api/movie/1
        [HttpDelete]
        public IHttpActionResult DeleteMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            return Ok(movie);
        }

    }
}

Vidly/Vidly/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.DTO;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class RentalController : Controller
    {
        private ApplicationDbContext _context;
        public RentalController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult New()
        {
            return View();
        }
        // GET: Rental
        public ActionResult Index()
        {
            NewRentalDTO rental = new NewRentalDTO();
            var movies = _context.Movies.ToList();
            rental.Movies = movies;
            rental.Movies.AsEnumerable().Select(o => new MovieModel
            {
                Id = o.Id,
                Name = o.Name
            });
            return View("RentalForm", rental);
        }

        public ActionResult Create(NewRentalDTO rentalDTO)
        {
            if (!ModelState.IsValid)
            {
                var movieLst = _context.Movies.ToList();
                rentalDTO.Movies = movieLst;
                rentalDTO.Movies.AsEnumerable().Select(o => new MovieModel
                {
                    Id = o.Id,
                    Name = o.Name
                });
                return View("RentalForm", rentalDTO);
            }

            
            var customerAdd = _context.Customers.SingleOrDefault(c => c.Id == rentalDTO.CustomerId);
            if (customerAdd != null)
            {
                foreach (var movie in rentalDTO.MovieIds)
                {
                    Rental rental = new Rental();
                    rental.customer = customerAdd;
                    //int id = int.Parse(movie);
                    rental.movie = _context.Movies.SingleOrDefault(c => c.Id == movie);
                    rental.DateRented = DateTime.Now;
                    _context.Rentals.Add(rental);                  

                }
                _context.SaveChanges();              
            }
           
            var movies = _context.Movies.ToList();
            rentalDTO.Movies = movies;
            rentalDTO.Movies.AsEnumerable().Select(o => new MovieModel
            {
                Id = o.Id,
                Name = o.Name
            });

            return View("RentalForm", rentalDTO);
        }
    }
}

Vidly/Vidly/Views/Shared/_Layout.cshtml
@*@model Vidly.ViewModels.RandomMovieViewModel*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Vidly/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "New", "Rental")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>